name: infinity_canvas
description: High-performance infinite canvas for Flutter with layered rendering and controller-driven camera/item APIs.
version: 0.8.1
homepage: https://github.com/vento007/infinity_canvas
repository: https://github.com/vento007/infinity_canvas
issue_tracker: https://github.com/vento007/infinity_canvas/issues
topics:
  - canvas
  - infinite-canvas
  - node-editor
  - zoom-pan
  - diagram-editor

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
